### ISSUE TITLE
Can't run flask_app.py, Error：arch_list[-1] += '+PTX' IndexError: list index out of range

### ISSUE THREAD

**Issue by Ikaros-521** [endo-yuki-t/UserControllableLT#3]
# system：Ubuntu
```
Successfully installed torch-1.9.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
(base) root@autodl-container-acda11befa-2e27ffe1:~/autodl-tmp/UserControllableLT# python interface/flask_app.py --checkpoint_path=pretrained_models/latent_transformer/cat.pt
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "interface/flask_app.py", line 15, in <module>
    from inference import demo
  File "/root/autodl-tmp/UserControllableLT/interface/inference.py", line 10, in <module>
    from models.StyleGANControler import StyleGANControler
  File "/root/autodl-tmp/UserControllableLT/./models/StyleGANControler.py", line 4, in <module>
    from models.stylegan2.model import Generator
  File "/root/autodl-tmp/UserControllableLT/./models/stylegan2/model.py", line 7, in <module>
    from models.stylegan2.op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "/root/autodl-tmp/UserControllableLT/./models/stylegan2/op/__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "/root/autodl-tmp/UserControllableLT/./models/stylegan2/op/fused_act.py", line 9, in <module>
    fused = load(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1080, in load
    return _jit_compile(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1293, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1392, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1783, in _write_ninja_file_to_build_library
    cuda_flags = common_cflags + COMMON_NVCC_FLAGS + _get_cuda_arch_flags()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1562, in _get_cuda_arch_flags
    arch_list[-1] += '+PTX'
IndexError: list index out of range

```
![image](https://github.com/endo-yuki-t/UserControllableLT/assets/40910637/9e42a381-e388-4d2a-93b8-a5486220cd19)
![image](https://github.com/endo-yuki-t/UserControllableLT/assets/40910637/77497181-ad94-455f-bb1d-1138e0e7dc3b)

# win10
![image](https://github.com/endo-yuki-t/UserControllableLT/assets/40910637/ca95c0bb-95cf-4987-8a27-b2b9c326d6a9)
![image](https://github.com/endo-yuki-t/UserControllableLT/assets/40910637/b0741bd1-3789-4779-9489-d9d8b1227ee6)

**Comment by Asuka001100** [comment]
你好，我也是这个问题，请问你现在解决了吗？

**Comment by Ikaros-521** [comment]
> 你好，我也是这个问题，请问你现在解决了吗？

没，直接换DragGAN了
